name: Release

on:
  push:
    branches:
      - "main"
      - "release-candidate"
      - "feature/plat-643-build-prototype"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Repo
        uses: actions/checkout@v2
      -
        name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      -
        name: Install Dependencies
        run: pnpm
      -
        name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Create pull request
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}