name: Release

on:
  push:
    branches:
      - "feature/plat-643-build-prototype"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Repo
        uses: actions/checkout@v2
      -
        name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      -
        name: Install Dependencies
        run: pnpm
      -
        name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: "chore: release"
          title: "chore: release"
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
